### ISSUE TITLE
Course Assignment for February 15th

### ISSUE THREAD

**Issue by natenolting** [KQuinlan802/BUAD3283-Work#6]
Please update per assignment notes at https://github.com/natenolting/BUAD-3283-E-Commerce-Web-Development/blob/spring2018/course_assignment/course_assignment_12_February_15.md

* [x] 1. Create a file `index.php` in `assignments/February_15`. This will be the entry point to your template.
* [x] 2. Format basic html elements doctype, html, head, body.
* [x] 3. Modularize elements on your template (Masthead, Navigation, Content, Footer, et al.)
* [x] 4. Create a dynamic navigation for your template.
* [x] 5. Create a mechanism where page content can be passed in dynamically via url
* [x] 6. Style the different template modules.

Please update these so I can grade this assignment.

**Comment by paulbunyannet** [comment]
@KQuinlan802 if you have these done can you check them off and close this issue? I think you have these done.

**Comment by natenolting** [comment]
Oops, using my work account, that was me above.

**Comment by KQuinlan802** [comment]
Whoops sorry about that!
